repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: trailing-whitespace
          name: Removing trailing white space 
          exclude: 'deprecated/|scripts/'
    # isort should run before black as black sometimes tweaks the isort output
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
      -   id: isort
          name: Formatting import blocks 
          exclude: 'deprecated/|scripts/'
          args: [--settings-path=pyproject.toml]
      # https://github.com/python/black#version-control-integration
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        - id: black
          name:  Make Code Look Pretty 
          language_version: python3.9
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
        name: Flake8 bug and error checks
        exclude: 'deprecated/|scripts/'
